### ISSUE TITLE
Searching & Sleeping to search uses %25 cpu

### ISSUE THREAD

**Issue by EmrecanD** [raulrene/Twitter-ContestJS-bot#16]
I tried this on W7 64 bit ultimate and W8.1 64 bit.

Same case. It uses %25 of the cpu when searching for tweets, and sleeping to search for tweets. Thats %25 cpu usage, for 1.5-2 min straight, every 10-15 minutes, for a simple script.

**Comment by raulrene** [comment]
It's not ideal the way it is written. I have in plan a rewriting of it using ES6 and Promises, and will do it in the near future when I have the time. 

It was written as a fun-to-do activity in 2-3 hours, and I wanted to keep it as simple as possible, meaning that it uses pure JS with no helper libraries and stuff, so things like sleeping and manual processing were much heavier.
