### ISSUE TITLE
Retweeting specific accounts

### ISSUE THREAD

**Issue by charliehoward** [raulrene/Twitter-ContestJS-bot#17]
Is there a way I can specify certain accounts to enter contests on so I only win stuff I actually want?

**Comment by raulrene** [comment]
Do you mean filtering by contest type? No, there isn't something like this, but we could make an extra filter by certain keywords. Or do you mean to only participate in contests made by certain accounts you know have stuff you're interested in?

**Comment by charliehoward** [comment]
Either would be good, although I specifically meant certain accounts.

**Comment by raulrene** [comment]
Hi @charliehoward ,

I managed to take some time today to change 1 or 2 things and I added the option to configure certain preferred accounts. These need to be configured in the `config.js` file under `preferred_accounts`.

**Comment by charliehoward** [comment]
In the box do I have type @ then the handle, or just the handle?

**Comment by raulrene** [comment]
It's an array and it doesn't need `@`. Just something like ["oneaccount", "anotheraccount", "anotherusername", "charliehoward"], etc

**Comment by charliehoward** [comment]
Ah okay, thanks! I'll give it ago.
