### ISSUE TITLE
Follower De-following

### ISSUE THREAD

**Issue by Zen00** [raulrene/Twitter-ContestJS-bot#6]
Eventually you'll fill up your allotted following list. Any way to auto de-follow people as you reach a certain amount of follows? Like whenever you follow 1000 people it will unfollow the oldest 100 followers?

**Comment by ps6000** [comment]
Looks like the twitter API will list the followers in the order they are followed but may end up reordering them at some point.

https://dev.twitter.com/rest/reference/get/followers/list

then using the post friendships/destroy you can unfollow an account
https://dev.twitter.com/rest/reference/post/friendships/destroy

I am not sure about an automated script, but maybe a cleanup script could be run that would get a list of users and then remove those users from the list?
