### ISSUE TITLE
Porn Retweets

### ISSUE THREAD

**Issue by Zen00** [raulrene/Twitter-ContestJS-bot#8]
I've had several instances where the bot will pick up porn that has been formulated to contain the retweet/win keywords. This is another instance where some better filters will be useful.

**Comment by henhouse** [comment]
I don't think there's a simple way around this. I mean, you could exclude tweets that contain a photo, but I am sure many contests contain media showing what will be won, etc. There's no real way to determine this... furthermore that kind of material isn't allowed on Twitter so it just hopefully gets reported and removed.
