### ISSUE TITLE
last_tweet_id

### ISSUE THREAD

**Issue by Zen00** [raulrene/Twitter-ContestJS-bot#9]
I'll say how I think this is supposed to work, hopefully I'm thinking right.

var last_tweet_id = 661669688620007400

If you put a tweet id into there, the app will tweet all new tweets until it get to this tweet number, then stop.

I hope that's how it works. If so then it's not working.

**Comment by raulrene** [comment]
From the API Documentation

> Twitter will only return Tweets with IDs higher than the value passed for **since_id**

This means that if you set since_id, only tweets which have the ID greater are returned. This does not mean, however, that tweets already tweeted before that have the ID > last_tweet_id are excluded. Because they are not fetched in ascending order of their IDs
